// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0S34Ec3WyC9EJYTgZWDQkDmN19GqD438',
    appId: '1:301746603364:android:dc7ee5282793c205d16671',
    messagingSenderId: '301746603364',
    projectId: 'evently-app-p15',
    storageBucket: 'evently-app-p15.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnOnYRF-qfvveqyC43ieikcbzUWutE6ro',
    appId: '1:301746603364:web:639e55b5e274c25fd16671',
    messagingSenderId: '301746603364',
    projectId: 'evently-app-p15',
    authDomain: 'evently-app-p15.firebaseapp.com',
    storageBucket: 'evently-app-p15.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwuppy9IYS3yg6OvPTZgPvs7iFYooZvPs',
    appId: '1:301746603364:ios:7a3fada8e3441fefd16671',
    messagingSenderId: '301746603364',
    projectId: 'evently-app-p15',
    storageBucket: 'evently-app-p15.firebasestorage.app',
    iosBundleId: 'com.example.projectEvently',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwuppy9IYS3yg6OvPTZgPvs7iFYooZvPs',
    appId: '1:301746603364:ios:7a3fada8e3441fefd16671',
    messagingSenderId: '301746603364',
    projectId: 'evently-app-p15',
    storageBucket: 'evently-app-p15.firebasestorage.app',
    iosBundleId: 'com.example.projectEvently',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnOnYRF-qfvveqyC43ieikcbzUWutE6ro',
    appId: '1:301746603364:web:66a1c2fb3b2a5a59d16671',
    messagingSenderId: '301746603364',
    projectId: 'evently-app-p15',
    authDomain: 'evently-app-p15.firebaseapp.com',
    storageBucket: 'evently-app-p15.firebasestorage.app',
  );

}